### ISSUE TITLE
I can't get statistics

### ISSUE THREAD

**Issue by mariuszkobak** [SvenSommer/MMM-GoogleAnalytics#2]
Hi,

I've followed all installation instructions and can't figure it out.
Module is loaded. I can't see any errors for npm start dev.
I can see only displayed header but no data for statistics.

What can be wrong?

**Comment by SvenSommer** [comment]
Can you please 
- set debug to true in the config.js file of your MMM-GoogleAnalytics tool. 
- Disable all other modules (by comment them out in the config.js file) 
- provide the console output, when starting the magic mirror framework. 

Thanks,
Robert

**Comment by SvenSommer** [comment]
P.s. Please be sure to erase all of your email, Passwort and google tracking informations  before posting it here!!

**Comment by mariuszkobak** [comment]
`  metrics: 'ga:newusers, ga:users, ga:sessions, ga:pageviews,  ga:sessionDuration',
  'start-date': 'today',
  'end-date': 'today',
  dimensions: 'ga:country',
  sort: '-ga:timeOnPage',
  filters: 'ga:timeOnPage>10',
  'start-index': 1,
  'max-results': 50 }
{ Error: Sort key ga:timeonpage is not a dimension or metric in this query.
    at Request._callback (/home/pi/MagicMirror/modules/MMM-GoogleAnalytics/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-GoogleAnalytics/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAnalytics/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAnalytics/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 400,
  errors: 
   [ { domain: 'global',
       reason: 'badRequest',
       message: 'Sort key ga:timeonpage is not a dimension or metric in this query.' } ] }
`

**Comment by mariuszkobak** [comment]
metrics: 'ga:newusers, ga:users, ga:sessions, ga:pageviews,  ga:sessionDuration',
  'start-date': 'today',
  'end-date': 'today',
  dimensions: 'ga:country',
  sort: '-ga:timeOnPage',
  filters: 'ga:timeOnPage>10',
  'start-index': 1,
  'max-results': 50 }
{ Error: Sort key ga:timeonpage is not a dimension or metric in this query.
    at Request._callback (/home/pi/MagicMirror/modules/MMM-GoogleAnalytics/node_modules/google-auth-library/lib/transporters.js:85:15)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-GoogleAnalytics/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAnalytics/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-GoogleAnalytics/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 400,
  errors: 
   [ { domain: 'global',
       reason: 'badRequest',
       message: 'Sort key ga:timeonpage is not a dimension or metric in this query.' } ] }

**Comment by SvenSommer** [comment]
Ok, this seems to be clear.
You query is not working. The google API responds with a "bad Request". You have to add the "timeonpage" variable also to the metric or dimension section. Otherwise no sorting is possible for the google API. To check if your query is valid, please use the query explorer: https://ga-dev-tools.appspot.com/query-explorer/

**Comment by mariuszkobak** [comment]
Where exactly should I add it? In which place?

**Comment by SvenSommer** [comment]
In the MMM-GoogleAnalytics part of your config.js file under metrics.

**Comment by mariuszkobak** [comment]
Thanks for support!
Right now I can see stats.

I want to display locations from google analytics on MMM-Globe.
Below are details from my config.js for both modules.

Still on Globe I can see only default locations, not from google analytics.
What can be wrong?

{
		module: 'MMM-Globe',
classes: 'default',
		position: 'lower_third',	// This can be any of the regions. Best results in lower_third
		config: {
                size:"medium", // Globe size. See configuration options below for more options
		receiveExternalLocations: 1,
                locations: [ 
                    // Fill with location Objects if desired
                    // e.g.
                    // {lat:37.77493,lng:-122.41942, label: "San Francisco"},
                    // {lat:-23.5475,lng:-46.63611, label: "Sao Paulo"}
                    // Individual values must be seperated by a comma. 
                    // You can look up the latitude and longitude for a specific location on Google Maps.
                ]
		}
	},

{
        module: 'MMM-GoogleAnalytics',
        header: 'KierunekWolnosc.pl - Statystyki',
        position: 'top_right',
classes: 'default',
        config: {
            viewID : 'ga:XXXXXXXXXX', // see README.md, how to get viewID and your keyfile.json
            start_date: 'today', //today,1daysAgo,
            end_date: 'today',
            metrics: 'ga:newusers, ga:users, ga:sessions, ga:pageviews, ga:sessionDuration, ga:timeOnPage',
			dimensions: 'ga:city, ga:country', //ga:country, ga:city,ga:source
			sort: '-ga:timeOnPage',
			filters: 'ga:timeOnPage>10', //ga:timeOnPage>10 Return results where the time on the page is strictly greater than ten seconds.
			segment: '',
			start_index: 1,
			max_results: 50,
			updateInterval: 1 * 10 * 1000, // every minute
			showtable: true,
            showtotalline: true,
			exportdatatoMMM_Globe: true,
			debug: false
            }
        },

**Comment by SvenSommer** [comment]
Ok, this looks like a bug. 
Please try 'ga:city, ga:country' also for the metrics section.

**Comment by mariuszkobak** [comment]
After adding 'ga:city, ga:country' in metrics nothing has changed. I can't see these locations on rotating globe.

**Comment by SvenSommer** [comment]
Ok, thanks. I'll check this. 
Currently I'm quite busy, realistically I'm gonna have a look in about three weeks.

**Comment by SvenSommer** [comment]
Hi,
finally I found some time to have a look.

Please try with the following config entry:
```
{
	module: 'MMM-Globe',
	position: 'lower_third',	// This can be any of the regions. Best results in lower_third
	config: {
			size:"medium",
			viewAngle:30,
			dayLength: 20,
			introLinesDuration: 2000,
			receiveExternalLocations: 1,
			locations: []
		}
	},
{
		module: 'MMM-GoogleAnalytics',
		position: 'top_left',
		config: {
			viewID : 'ga:XXXXXXX', //insert your ID
			start_date: 'today', //today,1daysAgo,
			end_date: 'today',
			metrics: 'ga:newusers,ga:users, ga:sessions, ga:pageviews,  ga:timeOnPage',
			dimensions: 'ga:country',
			sort: '-ga:timeOnPage',
			filters: 'ga:timeOnPage>10', //ga:timeOnPage>10 Return results where the time on the page is strictly greater than ten seconds.
			segment: '',
			start_index: 1,
			max_results: 50,
			updateInterval: 1 * 10 * 1000, // every minute
			showtotalline: true,
			showtable: false,
			exportdatatoMMM_Globe: true,
			debug: true
		}
},
```
