### ISSUE TITLE
Error badRequest

### ISSUE THREAD

**Issue by robbinonline** [SvenSommer/MMM-GoogleAnalytics#3]
`  errors: 
   [ { domain: 'global',
       reason: 'badRequest',
       message: 'Sort key ga:timeonpage is not a dimension or metric in this query.' } ] }`

I get the following error, any idea how to fix this?

**Comment by SvenSommer** [comment]
Hey robbinonline,
This error is generated as a result from googles api. You can prevent such errors by testing your query against the [Query Explorer](https://ga-dev-tools.appspot.com/query-explorer/).
If you’re able to get a result without an error just copy everything (metrics, dimensions, etc. ) to your configfile.

The error translated says: “Put the ga:timeonpage Variable also in your output if you want to sort by it.”

Solution:
Put „ga:timeonpage“ to your dimensions or metrics section of the MMM-GoogleAnalytics section in your configfile.

Have fun with it,
Robert
